services:
  mongodb:
    image: mongo:7
    container_name: agentflow-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh","--eval","db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes: 
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: agentflow-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

volumes: 
  mongo-data: 
  redis-data:

